kind: List
apiVersion: v1
items:
- kind: Secret
  apiVersion: v1
  metadata:
    name: quay-build-secret
  data:
    .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoicGFuYmFsYWciLCJwYXNzd29yZCI6IkRpNWI1c2UyISIsImVtYWlsIjoicGFuYmFsYWdAcmVkaGF0LmNvbSIsImF1dGgiOiJjR0Z1WW1Gc1lXYzZSR2sxWWpWelpUSWgifX19
  type: kubernetes.io/dockerconfigjson

